version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: visitorcounter
      POSTGRES_USER: counteruser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: on-failure

  app:
    image: adanchristian/cadan-abb:v1
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://counteruser:password@postgres:5432/visitorcounter
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started

